// Script to add 15 new listings to Firestore
// Run with: node addListings.js

const { initializeApp } = require('firebase/app');
const { getFirestore, collection, addDoc, getDocs, query, where } = require('firebase/firestore');

// Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyDeAQnBx42gTbNdEO60L4JFzPyiFOt51W4",
  authDomain: "nimbus-207d9.firebaseapp.com",
  projectId: "nimbus-207d9",
  storageBucket: "nimbus-207d9.firebasestorage.app",
  messagingSenderId: "452942433901",
  appId: "1:452942433901:web:3b013740a4784a24fcf964",
  measurementId: "G-VCTWMCE5HT"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// Hardware images for listings
const hardwareImages = [
  "https://www.pny.com/productimages/F8BA18E3-C163-4BD4-B679-AFD300CBCE8D/images/L4_3QTR-Top-Left.png",
  "https://www.amax.com/content/images/2024/04/AceleMax-X-88-CH200.png",
  "https://www.servethehome.com/wp-content/uploads/2021/07/Inspur-NF5488A5-NVIDIA-HGX-A100-8-GPU-Assembly-8x-A100-2.jpg",
  "https://www.leadtek.com/p_images/zoom/40956_1Z.jpg",
  "https://m.opticaltransceiver-module.com/photo/pt171948695-nvidia_a10_tensor_core_gpu_with_good_price_in_stock_from_china.jpg"
];

const getImage = (index) => hardwareImages[index % hardwareImages.length];

// 15 realistic listings matching the CreateListing form structure
const newListings = [
  {
    sellerId: "", // Will be set from existing seller
    sellerName: "Hardware Solutions Inc",
    // Server Photos
    frontPhoto: getImage(0),
    backPhoto: getImage(1),
    serialPhoto: getImage(2),
    poweredOnPhoto: getImage(3),
    // Proof of Ownership
    ownershipProof: "https://example.com/docs/invoice_h100_001.pdf",
    ownershipType: "invoice",
    // Warranty
    warrantyDocument: "https://example.com/docs/warranty_h100_001.pdf",
    warrantyStatus: "active",
    // Technical Specifications
    quantity: 3,
    chassis: "Dell PowerEdge R750xa",
    gpuModel: "H100",
    gpuCount: "8",
    cpuModel: "Intel Xeon Gold 6338",
    cpuCount: "2",
    ram: "512",
    storage: "2TB NVMe SSD",
    networking: "Dual 25Gb Ethernet",
    cooling: "air",
    yearOfPurchase: "2023",
    physicalLocation: "United States",
    condition: "used",
    conditionNote: "Used for 8 months in AI training cluster, excellent condition",
    // Test Reports
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_h100_001.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_h100_001.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_h100_001.pdf",
    // Video
    verificationVideo: "https://example.com/videos/verification_h100_001.mp4",
    // Status
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-15'),
    approvedAt: new Date('2024-01-16'),
  },
  {
    sellerId: "",
    sellerName: "Compute Dynamics",
    frontPhoto: getImage(1),
    backPhoto: getImage(2),
    serialPhoto: getImage(3),
    poweredOnPhoto: getImage(4),
    ownershipProof: "https://example.com/docs/invoice_h200_001.pdf",
    ownershipType: "invoice",
    warrantyDocument: "https://example.com/docs/warranty_h200_001.pdf",
    warrantyStatus: "active",
    quantity: 2,
    chassis: "Supermicro SYS-421GE-TNRT",
    gpuModel: "H200",
    gpuCount: "4",
    cpuModel: "AMD EPYC 7763",
    cpuCount: "2",
    ram: "256",
    storage: "1TB NVMe SSD",
    networking: "Dual 100Gb InfiniBand",
    cooling: "liquid",
    yearOfPurchase: "2024",
    physicalLocation: "United Kingdom",
    condition: "new",
    conditionNote: "Brand new, never deployed, factory sealed",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_h200_001.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_h200_001.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_h200_001.pdf",
    verificationVideo: "https://example.com/videos/verification_h200_001.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-16'),
    approvedAt: new Date('2024-01-17'),
  },
  {
    sellerId: "",
    sellerName: "Hardware Solutions Inc",
    frontPhoto: getImage(2),
    backPhoto: getImage(3),
    serialPhoto: getImage(4),
    poweredOnPhoto: getImage(0),
    ownershipProof: "https://example.com/docs/invoice_a100_001.pdf",
    ownershipType: "invoice",
    warrantyDocument: "https://example.com/docs/warranty_a100_001.pdf",
    warrantyStatus: "active",
    quantity: 5,
    chassis: "HPE ProLiant DL380 Gen10",
    gpuModel: "A100",
    gpuCount: "8",
    cpuModel: "Intel Xeon Gold 6248R",
    cpuCount: "2",
    ram: "512",
    storage: "3.84TB NVMe SSD",
    networking: "Dual 10Gb Ethernet",
    cooling: "air",
    yearOfPurchase: "2022",
    physicalLocation: "United States",
    condition: "used",
    conditionNote: "Used for 12 months in data center, well maintained",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_a100_001.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_a100_001.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_a100_001.pdf",
    verificationVideo: "https://example.com/videos/verification_a100_001.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-17'),
    approvedAt: new Date('2024-01-18'),
  },
  {
    sellerId: "",
    sellerName: "AI Server Warehouse",
    frontPhoto: getImage(3),
    backPhoto: getImage(4),
    serialPhoto: getImage(0),
    poweredOnPhoto: getImage(1),
    ownershipProof: "https://example.com/docs/invoice_b200_001.pdf",
    ownershipType: "decommission",
    warrantyDocument: "https://example.com/docs/warranty_b200_001.pdf",
    warrantyStatus: "active",
    quantity: 1,
    chassis: "NVIDIA DGX B200",
    gpuModel: "B200",
    gpuCount: "8",
    cpuModel: "AMD EPYC 9654",
    cpuCount: "2",
    ram: "1024",
    storage: "4TB NVMe SSD",
    networking: "Dual 400Gb InfiniBand",
    cooling: "liquid",
    yearOfPurchase: "2024",
    physicalLocation: "Germany",
    condition: "new",
    conditionNote: "Brand new, factory direct",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_b200_001.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_b200_001.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_b200_001.pdf",
    verificationVideo: "https://example.com/videos/verification_b200_001.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-18'),
    approvedAt: new Date('2024-01-19'),
  },
  {
    sellerId: "",
    sellerName: "Compute Dynamics",
    frontPhoto: getImage(4),
    backPhoto: getImage(0),
    serialPhoto: getImage(1),
    poweredOnPhoto: getImage(2),
    ownershipProof: "https://example.com/docs/invoice_h100_002.pdf",
    ownershipType: "invoice",
    warrantyDocument: "https://example.com/docs/warranty_h100_002.pdf",
    warrantyStatus: "expired",
    quantity: 4,
    chassis: "Lenovo ThinkSystem SR670 V2",
    gpuModel: "H100",
    gpuCount: "8",
    cpuModel: "Intel Xeon Gold 6430",
    cpuCount: "2",
    ram: "512",
    storage: "2TB NVMe SSD",
    networking: "Dual 25Gb Ethernet",
    cooling: "air",
    yearOfPurchase: "2023",
    physicalLocation: "Canada",
    condition: "used",
    conditionNote: "Used for 10 months, excellent working condition",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_h100_002.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_h100_002.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_h100_002.pdf",
    verificationVideo: "https://example.com/videos/verification_h100_002.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-19'),
    approvedAt: new Date('2024-01-20'),
  },
  {
    sellerId: "",
    sellerName: "Hardware Solutions Inc",
    frontPhoto: getImage(0),
    backPhoto: getImage(1),
    serialPhoto: getImage(2),
    poweredOnPhoto: getImage(3),
    ownershipProof: "https://example.com/docs/invoice_v100_001.pdf",
    ownershipType: "consignment",
    warrantyDocument: "https://example.com/docs/warranty_v100_001.pdf",
    warrantyStatus: "expired",
    quantity: 6,
    chassis: "Dell PowerEdge R740",
    gpuModel: "V100",
    gpuCount: "4",
    cpuModel: "Intel Xeon Gold 6248",
    cpuCount: "2",
    ram: "256",
    storage: "1.92TB NVMe SSD",
    networking: "Dual 10Gb Ethernet",
    cooling: "air",
    yearOfPurchase: "2021",
    physicalLocation: "United States",
    condition: "refurbished",
    conditionNote: "Refurbished and tested, all components verified working",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_v100_001.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_v100_001.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_v100_001.pdf",
    verificationVideo: "https://example.com/videos/verification_v100_001.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-20'),
    approvedAt: new Date('2024-01-21'),
  },
  {
    sellerId: "",
    sellerName: "AI Server Warehouse",
    frontPhoto: getImage(1),
    backPhoto: getImage(2),
    serialPhoto: getImage(3),
    poweredOnPhoto: getImage(4),
    ownershipProof: "https://example.com/docs/invoice_h200_002.pdf",
    ownershipType: "invoice",
    warrantyDocument: "https://example.com/docs/warranty_h200_002.pdf",
    warrantyStatus: "active",
    quantity: 2,
    chassis: "Supermicro AS-4124GO-NART",
    gpuModel: "H200",
    gpuCount: "8",
    cpuModel: "AMD EPYC 9654",
    cpuCount: "2",
    ram: "512",
    storage: "2TB NVMe SSD",
    networking: "Dual 200Gb InfiniBand",
    cooling: "liquid",
    yearOfPurchase: "2024",
    physicalLocation: "France",
    condition: "new",
    conditionNote: "Brand new, unopened boxes",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_h200_002.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_h200_002.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_h200_002.pdf",
    verificationVideo: "https://example.com/videos/verification_h200_002.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-21'),
    approvedAt: new Date('2024-01-22'),
  },
  {
    sellerId: "",
    sellerName: "Compute Dynamics",
    frontPhoto: getImage(2),
    backPhoto: getImage(3),
    serialPhoto: getImage(4),
    poweredOnPhoto: getImage(0),
    ownershipProof: "https://example.com/docs/invoice_a100_002.pdf",
    ownershipType: "invoice",
    warrantyDocument: "https://example.com/docs/warranty_a100_002.pdf",
    warrantyStatus: "active",
    quantity: 3,
    chassis: "ASUS ESC8000 G4",
    gpuModel: "A100",
    gpuCount: "8",
    cpuModel: "Intel Xeon Gold 6338",
    cpuCount: "2",
    ram: "512",
    storage: "3.84TB NVMe SSD",
    networking: "Dual 25Gb Ethernet",
    cooling: "air",
    yearOfPurchase: "2023",
    physicalLocation: "United Kingdom",
    condition: "used",
    conditionNote: "Used for 6 months in research lab",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_a100_002.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_a100_002.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_a100_002.pdf",
    verificationVideo: "https://example.com/videos/verification_a100_002.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-22'),
    approvedAt: new Date('2024-01-23'),
  },
  {
    sellerId: "",
    sellerName: "Hardware Solutions Inc",
    frontPhoto: getImage(3),
    backPhoto: getImage(4),
    serialPhoto: getImage(0),
    poweredOnPhoto: getImage(1),
    ownershipProof: "https://example.com/docs/invoice_h100_003.pdf",
    ownershipType: "invoice",
    warrantyDocument: "https://example.com/docs/warranty_h100_003.pdf",
    warrantyStatus: "active",
    quantity: 1,
    chassis: "Gigabyte G292-Z43",
    gpuModel: "H100",
    gpuCount: "8",
    cpuModel: "AMD EPYC 7763",
    cpuCount: "2",
    ram: "512",
    storage: "2TB NVMe SSD",
    networking: "Dual 25Gb Ethernet",
    cooling: "air",
    yearOfPurchase: "2023",
    physicalLocation: "United States",
    condition: "used",
    conditionNote: "Lightly used for 4 months",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_h100_003.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_h100_003.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_h100_003.pdf",
    verificationVideo: "https://example.com/videos/verification_h100_003.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-23'),
    approvedAt: new Date('2024-01-24'),
  },
  {
    sellerId: "",
    sellerName: "AI Server Warehouse",
    frontPhoto: getImage(4),
    backPhoto: getImage(0),
    serialPhoto: getImage(1),
    poweredOnPhoto: getImage(2),
    ownershipProof: "https://example.com/docs/invoice_b200_002.pdf",
    ownershipType: "decommission",
    warrantyDocument: "https://example.com/docs/warranty_b200_002.pdf",
    warrantyStatus: "active",
    quantity: 2,
    chassis: "NVIDIA DGX B200",
    gpuModel: "B200",
    gpuCount: "8",
    cpuModel: "AMD EPYC 9654",
    cpuCount: "2",
    ram: "1024",
    storage: "4TB NVMe SSD",
    networking: "Dual 400Gb InfiniBand",
    cooling: "liquid",
    yearOfPurchase: "2024",
    physicalLocation: "Netherlands",
    condition: "new",
    conditionNote: "Brand new, factory sealed",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_b200_002.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_b200_002.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_b200_002.pdf",
    verificationVideo: "https://example.com/videos/verification_b200_002.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-24'),
    approvedAt: new Date('2024-01-25'),
  },
  {
    sellerId: "",
    sellerName: "Compute Dynamics",
    frontPhoto: getImage(0),
    backPhoto: getImage(1),
    serialPhoto: getImage(2),
    poweredOnPhoto: getImage(3),
    ownershipProof: "https://example.com/docs/invoice_h200_003.pdf",
    ownershipType: "invoice",
    warrantyDocument: "https://example.com/docs/warranty_h200_003.pdf",
    warrantyStatus: "active",
    quantity: 4,
    chassis: "Supermicro SYS-421GE-TNRT",
    gpuModel: "H200",
    gpuCount: "4",
    cpuModel: "AMD EPYC 7763",
    cpuCount: "2",
    ram: "256",
    storage: "1TB NVMe SSD",
    networking: "Dual 100Gb InfiniBand",
    cooling: "liquid",
    yearOfPurchase: "2024",
    physicalLocation: "United Kingdom",
    condition: "new",
    conditionNote: "Brand new, never deployed",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_h200_003.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_h200_003.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_h200_003.pdf",
    verificationVideo: "https://example.com/videos/verification_h200_003.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-25'),
    approvedAt: new Date('2024-01-26'),
  },
  {
    sellerId: "",
    sellerName: "Hardware Solutions Inc",
    frontPhoto: getImage(1),
    backPhoto: getImage(2),
    serialPhoto: getImage(3),
    poweredOnPhoto: getImage(4),
    ownershipProof: "https://example.com/docs/invoice_a100_003.pdf",
    ownershipType: "invoice",
    warrantyDocument: "https://example.com/docs/warranty_a100_003.pdf",
    warrantyStatus: "expired",
    quantity: 7,
    chassis: "HPE ProLiant DL380 Gen10",
    gpuModel: "A100",
    gpuCount: "8",
    cpuModel: "Intel Xeon Gold 6248R",
    cpuCount: "2",
    ram: "512",
    storage: "3.84TB NVMe SSD",
    networking: "Dual 10Gb Ethernet",
    cooling: "air",
    yearOfPurchase: "2022",
    physicalLocation: "United States",
    condition: "used",
    conditionNote: "Used for 18 months, all components tested and verified",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_a100_003.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_a100_003.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_a100_003.pdf",
    verificationVideo: "https://example.com/videos/verification_a100_003.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-26'),
    approvedAt: new Date('2024-01-27'),
  },
  {
    sellerId: "",
    sellerName: "AI Server Warehouse",
    frontPhoto: getImage(2),
    backPhoto: getImage(3),
    serialPhoto: getImage(4),
    poweredOnPhoto: getImage(0),
    ownershipProof: "https://example.com/docs/invoice_h100_004.pdf",
    ownershipType: "invoice",
    warrantyDocument: "https://example.com/docs/warranty_h100_004.pdf",
    warrantyStatus: "active",
    quantity: 2,
    chassis: "Dell PowerEdge R750xa",
    gpuModel: "H100",
    gpuCount: "8",
    cpuModel: "Intel Xeon Gold 6338",
    cpuCount: "2",
    ram: "512",
    storage: "2TB NVMe SSD",
    networking: "Dual 25Gb Ethernet",
    cooling: "air",
    yearOfPurchase: "2023",
    physicalLocation: "Germany",
    condition: "used",
    conditionNote: "Used for 7 months, excellent condition",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_h100_004.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_h100_004.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_h100_004.pdf",
    verificationVideo: "https://example.com/videos/verification_h100_004.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-27'),
    approvedAt: new Date('2024-01-28'),
  },
  {
    sellerId: "",
    sellerName: "Compute Dynamics",
    frontPhoto: getImage(3),
    backPhoto: getImage(4),
    serialPhoto: getImage(0),
    poweredOnPhoto: getImage(1),
    ownershipProof: "https://example.com/docs/invoice_v100_002.pdf",
    ownershipType: "consignment",
    warrantyDocument: "https://example.com/docs/warranty_v100_002.pdf",
    warrantyStatus: "expired",
    quantity: 8,
    chassis: "Dell PowerEdge R740",
    gpuModel: "V100",
    gpuCount: "4",
    cpuModel: "Intel Xeon Gold 6248",
    cpuCount: "2",
    ram: "256",
    storage: "1.92TB NVMe SSD",
    networking: "Dual 10Gb Ethernet",
    cooling: "air",
    yearOfPurchase: "2021",
    physicalLocation: "Canada",
    condition: "refurbished",
    conditionNote: "Refurbished with new thermal paste and fans, fully tested",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_v100_002.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_v100_002.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_v100_002.pdf",
    verificationVideo: "https://example.com/videos/verification_v100_002.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-28'),
    approvedAt: new Date('2024-01-29'),
  },
  {
    sellerId: "",
    sellerName: "Hardware Solutions Inc",
    frontPhoto: getImage(4),
    backPhoto: getImage(0),
    serialPhoto: getImage(1),
    poweredOnPhoto: getImage(2),
    ownershipProof: "https://example.com/docs/invoice_h200_004.pdf",
    ownershipType: "invoice",
    warrantyDocument: "https://example.com/docs/warranty_h200_004.pdf",
    warrantyStatus: "active",
    quantity: 1,
    chassis: "Supermicro AS-4124GO-NART",
    gpuModel: "H200",
    gpuCount: "8",
    cpuModel: "AMD EPYC 9654",
    cpuCount: "2",
    ram: "512",
    storage: "2TB NVMe SSD",
    networking: "Dual 200Gb InfiniBand",
    cooling: "liquid",
    yearOfPurchase: "2024",
    physicalLocation: "United States",
    condition: "new",
    conditionNote: "Brand new, factory direct, unopened",
    nvidiaSmiReport: "https://example.com/reports/nvidia-smi_h200_004.txt",
    diagnosticsReport: "https://example.com/reports/diagnostics_h200_004.pdf",
    benchmarkReport: "https://example.com/reports/benchmark_h200_004.pdf",
    verificationVideo: "https://example.com/videos/verification_h200_004.mp4",
    status: "active",
    verified: true,
    createdAt: new Date(),
    submittedAt: new Date('2024-01-29'),
    approvedAt: new Date('2024-01-30'),
  },
];

async function addListings() {
  try {
    console.log('🚀 Starting to add 15 new listings to Firestore...');

    // Get existing seller IDs
    console.log('👥 Fetching seller IDs...');
    const sellersQuery = query(collection(db, 'users'), where('userType', '==', 'seller'));
    const sellersSnapshot = await getDocs(sellersQuery);
    
    if (sellersSnapshot.empty) {
      console.error('❌ No sellers found in database. Please add sellers first.');
      process.exit(1);
    }

    const sellers = sellersSnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
    console.log(`✅ Found ${sellers.length} seller(s)`);

    // Distribute listings across sellers
    const sellerNames = ['Hardware Solutions Inc', 'Compute Dynamics', 'AI Server Warehouse'];
    const sellerMap = {};
    
    sellers.forEach(seller => {
      if (seller.companyName && sellerNames.includes(seller.companyName)) {
        sellerMap[seller.companyName] = seller.id;
      }
    });

    // If we don't have all sellers, use the first seller for all
    const defaultSellerId = sellers[0].id;
    const defaultSellerName = sellers[0].companyName || 'Hardware Solutions Inc';

    console.log('📋 Adding listings...');
    let addedCount = 0;

    for (let i = 0; i < newListings.length; i++) {
      const listing = { ...newListings[i] };
      
      // Set seller ID based on seller name
      if (sellerMap[listing.sellerName]) {
        listing.sellerId = sellerMap[listing.sellerName];
      } else {
        listing.sellerId = defaultSellerId;
        listing.sellerName = defaultSellerName;
      }

      // Add to listings collection
      const docRef = await addDoc(collection(db, 'listings'), listing);
      addedCount++;
      console.log(`✅ [${addedCount}/15] Added listing: ${listing.gpuModel} Server - ${listing.chassis} (ID: ${docRef.id})`);
    }

    console.log(`\n🎉 Successfully added ${addedCount} listings to Firestore!`);
    console.log('✅ All listings are active and verified.');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error adding listings:', error);
    process.exit(1);
  }
}

// Run the script
addListings();

